In [1]:
print ("Hello World")


Hello World


In [3]:
def testIndentation ():
    print("Hello Python")
    if True:
        print("true")
    else :
        print("false")
print("Learn Indentation")        

Learn Indentation


In [5]:
testIndentation()

Hello Python
true


In [6]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [7]:
-8//3

-3

In [8]:
-8//2

-4

In [2]:
!pip install numpy


Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))) - skipping


In [3]:
import numpy as np

In [6]:
arr1=np.array([1,2,3])

In [7]:
arr1

array([1, 2, 3])

In [8]:
type(arr1)

numpy.ndarray

In [9]:
arr1*2

array([2, 4, 6])

In [10]:
np.arange(1,5)

array([1, 2, 3, 4])

In [12]:
np.arange(1,15,2.5)

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5])

In [13]:
np.array(range(1,5))

array([1, 2, 3, 4])

In [15]:
arr2=np.array([0,10,100])
print(arr2**10)

[                  0         10000000000 7766279631452241920]


In [16]:
arr2.dtype


dtype('int64')

In [20]:
k=np.array([[1,2],[2,3]])

In [22]:
k.shape

(2, 2)

In [33]:
k=np.arange(1,13)

In [34]:
k.shape

(12,)

In [36]:
m=k.reshape(3,4)

In [37]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
m.ndim

2

In [40]:
z=np.zeros(3)

In [45]:
np.ones((1,3))*5

array([[5., 5., 5.]])

In [46]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [47]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
r=np.arange(0,12).reshape(3,4)

In [51]:
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
r[0]

array([0, 1, 2, 3])

In [53]:
r[0][0]

0

In [54]:
r[0,0]

0

In [55]:
r[0,1]

1

In [56]:
r[1,0]

4

In [57]:
r[0,1:3]

array([1, 2])

In [59]:
r[r%2==0]

array([ 0,  2,  4,  6,  8, 10])

In [60]:
r[r<6]

array([0, 1, 2, 3, 4, 5])

In [62]:
arr = np.array([2, 4, 6, 8, 10]) #1
c0 = arr #2
c0[0]= 12 #3
arr = np.array([2, 4, 6, 8, 10]) #4
c1 = arr.view() #5
arr[0] = 12 #6
arr = np.array([2, 4, 6, 8, 10]) #7
c2 = arr.copy() #8
arr[0] = 12 #9

In [64]:
c1,c2


(array([12,  4,  6,  8, 10]), array([ 2,  4,  6,  8, 10]))

In [65]:
c0,arr

(array([12,  4,  6,  8, 10]), array([12,  4,  6,  8, 10]))

In [66]:
c1,arr

(array([12,  4,  6,  8, 10]), array([12,  4,  6,  8, 10]))

In [72]:
arr=np.arange(5, 30, 2)
arr

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [71]:
b=a[a%3==0]
b

array([ 9, 15, 21, 27])

In [73]:
whfnc=np.where((arr<25) & (arr%3==0) & (arr%3==0))
arr[whfnc]

array([ 9, 15, 21])

In [74]:
arr[np.all([arr<25, arr%3==0, arr>5], axis=0)]

array([ 9, 15, 21])

In [81]:
boolArr = (arr < 25) & (arr>5) & (arr%3==0)
newArr = arr[boolArr]
newArr

array([ 9, 15, 21])

In [82]:
newArr = arr[(arr>5) & (arr<25) & (arr%3==0)]
newArr

array([ 9, 15, 21])

In [83]:
sampleArray = np.array([[1,2,3],[4,5,6],[7,8,9]])



In [84]:
sampleArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
arr = sampleArray[1,:]
sampleArray[:,1]=arr

In [86]:
sampleArray

array([[1, 4, 3],
       [4, 5, 6],
       [7, 6, 9]])

# Python Practice 

#Electricity Bill 
Problem Description

Given an integer A denoting the amount of units of electricity consumed, you have to calculate the electricity bill (in Rs.) with the help of the below charge conditions:

For first 50 units Rs. 0.50/unit
For next 100 units Rs. 0.75/unit
For next 100 units Rs. 1.20/unit
For unit above 250 Rs. 1.50/unit
An additional surcharge of 20% is added to the bill.


In [91]:
def main():
    # YOUR CODE GOES HERE
    # Please take input and print output to standard input/output (stdin/stdout)
    # E.g. 'input()/raw_input()' for input & 'print' for output

    return 0

if __name__ == '__main__':
    main()

bill=int(input())
if(bill>0 and bill<=50):
    sum=bill*.5
    total=sum+.2*sum
elif(bill>50 and bill<=100):
    sum=50*.5 +(bill-50)*.75
    total=sum+.2*sum
elif(bill>100 and bill<=200):
    sum=50*.5+(bill-50)*.75
    total=sum+.2*sum        
elif(bill>200 and bill<=250):
    sum=50*.5+100*.75 +(bill-150)*1.2
    total=sum+.2*sum        
elif(bill>250 ):
    sum=50*.5+100*.75 +100*1.2+(bill-250)*1.5
    total=sum+.2*sum   
else:
    sum=0
    total=0
print(int(total))    

120
93


#You have to tell whether it is a vowel or not.



In [93]:
def main():
    # YOUR CODE GOES HERE
    # Please take input and print output to standard input/output (stdin/stdout)
    # E.g. 'input()/raw_input()' for input & 'print' for output

    return 0

if __name__ == '__main__':
    main()
c = input()
if(c in ('a','e','i','o','u')):
    print(1)
else:
    print(0)   

t
0


In [94]:
#Perfect Square


In [100]:
import math
class Solution:
    # @param A : integer
    # @return an integer
    def solve(self, A):
        sq=math.sqrt(A)
        if(math.ceil(sq) == math.floor(sq)):
            return 1
        else:
            return 0    

In [108]:
x=1
Solution.solve(x,5)

0

In [109]:
from functools import reduce 
def main():
    
    # Use map to print the square of each numbers 
    my_ints = [4, 6, 3, 9, 2, 8, 12]
    
    # Use filter to print only the names that are less than or equal to seven letters
    my_names = ["scaler", "interviewbit", "rishabh", "student", "course"]
    
    # Use reduce to print the product of these numbers
    my_numbers = [4, 6, 9, 23, 5]
    
    # Fix all three respectively. 
    map_result = list(map(lambda x:x**2, my_ints))
    filter_result = list(filter(lambda name:len(name)<=7, my_names))
    reduce_result = reduce(lambda num1, num2: num1 * num2, my_numbers)
    
    print(map_result)
    print(filter_result)
    print(reduce_result)
    return 0